### ISSUE TITLE
Error: overloaded 'parseInt' leads to ambiguous calls

### ISSUE THREAD

**Issue by timotheecour** [oswjk/nimpb#4]
```
git clone https://github.com/oswjk/nimpb
cd nimpb
nimble install
/Users/timothee/git_clone/nim/nimpb/nimpb/json.nim(100, 6) Error: overloaded 'parseInt' leads to ambiguous calls
```

WORKAROUND: commented out parseInt in nimpb/nimpb/json.nim EDIT: that doesn't work with `nimble run_conformance_tests`

**Comment by oswjk** [comment]
Which version of nim is this with? I'm using latest stable release and haven't noticed. But yeah, some procs could be renamed a bit.

**Comment by MikeEmery** [comment]
I get this error on nim 0.19

**Comment by oswjk** [comment]
Yeah, I'll look into testing nimpb with 0.19 some day now. Have been on vacation so haven't had the time. :-)

**Comment by timotheecour** [comment]
it does, thanks! please merge :)

**Comment by MikeEmery** [comment]
Works for me too 👍
