### ISSUE TITLE
Could this be used for gRPC?

### ISSUE THREAD

**Issue by skunkiferous** [oswjk/nimpb#9]
Is it currently possible, and/or what would be required, to use your Nim implementation of protobuf with [gRPC](https://grpc.io/)?

**Comment by skunkiferous** [comment]
"It just takes a lot of effort to create a gRPC library." So, I assume it means I cannot simply reuse there C++ gRPC library; one would need a Nim version of that too. Since I was looking for a RPC system with a "security review", as it will be used with "untrusted clients", I'll have to look for alternatives. I guess I could just have C++ classes generated for the schema, and try to run nimgen on them (not sure if nimgen handles C++, or only C). Thanks for the reply.

**Comment by timotheecour** [comment]
broken link above; it should be: https://github.com/oswjk/nimtwirp

**Comment by timotheecour** [comment]
@oswjk I wanted to mention this, which was just released for D, maybe it could be of help:
* forum thread: [https://forum.dlang.org/post/rbsxuzadwvixuwbyaref@forum.dlang.org](hunt-grpc is Grpc for D programming language, hunt-http library based.)
* https://github.com/huntlabs/hunt-grpc 
* caveat: [streaming and bidirectional streaming grpc? · Issue #3 · huntlabs/hunt-grpc](https://github.com/huntlabs/hunt-grpc/issues/3)
